### ISSUE TITLE
Add platform helpers

### ISSUE THREAD

**Issue by YorVeX** [kostya9/NetObsBindings#17]
For pretty much the reason that OBS gives itself ("These functions/structures/types are used to perform actions that typically don’t have shared functions across different operating systems and platforms.") it would be good to have the [platform helper functions](https://docs.obsproject.com/reference-libobs-util-platform) available, for example os_gettime_ns() to be able to create the same timestamps that OBS is using itself.

[This should be the right header file](https://github.com/obsproject/obs-studio/blob/release/29.1/libobs/util/platform.h).

**Comment by kostya9** [comment]
Added the APIs, but found that some of them are not really compatible with how .NET does cross-platform. Some APIs write information (or return) to struct pointers that have different layouts in different platforms (e.g. CPU info, file stat info).

In C, this is handled by `#define` - it works since it is compiled to each platform separately.

So I recommend to use .NET APIs whenever possible (and added a notice to do that to `ObsPlatform` class XML documentation).

The new APIs are in [0.0.1.37-alpha](https://www.nuget.org/packages/NetObsBindings/0.0.1.37-alpha)

**Comment by YorVeX** [comment]
Ah, you're right, good find, still thanks a lot for implementing it!
